config/routes.rb
Rails.application.routes.draw do

  get "categories" => "categories#index"
  get "categories/new" => "categories#new"
  post "categories" => "categories#create"
  get "categories/:id" => "categories#show", as: "category"
  delete "/categories/:id" => "categories#destroy", as: "category_delete"

  get "members/index" => "members#index"

  get "members/new" => "memebers#new"

  get "members/create" => "members#create"

  get "welcome/index" => "welcome#index"

  get "users" => "users#index"
  get "users/new" => "users#new"
  post "users" => "users#create"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  resources :articles
  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
	end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, presence: true, confirmation: true, length: { in: 6..20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories =Category.all
  end

  def new
  	@category =Category.new 
  end

  def show 
    @category = Category.find(params[:id])
  end 

  def create
  	@category = Category.new(params.require(:category).permit(:name))
  	if @category.save
  		redirect_to categories_path
  	else
  		render :new
    end

  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category successfully deleted"}
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
  	@merbers = Member.all
  end

  def new
  	@member = Member.new
  end

  def create
  	
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.where(email: params[:login][:email]).first
		if user && user.authenticate(params[:login][:password])
			session[:user_id] = user.id.to_s
			redirect_to users_path
		else
			render :new
			
	end
end

	def destroy
		session.delete(:user_id)
		redirect_to login_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users =User.all
	end

	def new
		@user = User.new
	end

	def create
	@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to users_path
		else
			render :new
		end
	end
end

private

def user_params
	params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories</h1>

<ul>
	<% @categories.each do |c| %>
	<li><%= c.name %></li>
	<li><%= link_to "show", category_path(c.id) %></li>
	<li><%= link_to "delete", category_delete_path(c.id), method: :delete, data: {confirm: "are you sure?"} %>
	<% end %>
</ul>

app/views/categories/new.html.erb
<h1>categories</h1>



<%= form_for @category do |f| %>
<div>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
</div>
 <% end %>

app/views/categories/show.html.erb
<%= @category.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Projecto2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
  
</head>
<body>
 <%= yield %>
 <meta name="viewport" content="width=device-width, initial-scale=1">
</body>
</html>

app/views/members/create.html.erb
<h1>Members#create</h1>
<p>Find me in app/views/members/create.html.erb</p>

app/views/members/index.html.erb
<% @members.each do |member| %>
<%= member.name
<% end %>

app/views/members/new.html.erb
<h1>Members#new</h1>
<p>Find me in app/views/members/new.html.erb</p>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
	<% @users.each do |users| %>
	<li><%= users.name %></li>
	<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>

	<div>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>

	<div>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>

	<div>
		<%= f.submit %>
	</div>

<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to UNITE</h1>
<button>add member</button>
<button>edit member</button>
<button>logout</button>